### ISSUE TITLE
Create a simplified and configurable version

### ISSUE THREAD

**Issue by clausmullie** [Jefwillems/fish#2]
Hi @Jefwillems!

I really like this project and would love to configure my own version. 

I did some snooping around and noticed the following:
1) As this project was not intended for reuse, there is no configuration file, no signposts to variables and the code includes hard coded names for icons (ie in sketch.js)
2) You have separated the your development environment (most of master) and the production environment (/docs/) and use node to compile this

I'm planning to make a simplified version, including just the /docs/ content (increasing risk of breaking, but also simplifying, the project), reconfiguring the game, and documenting what I learn on the way. 

I'll be hacking in https://github.com/clausmullie/fish and will make a pull request for a configuration file once/if I'm done!

**Comment by clausmullie** [comment]
If I am not mistaken the variables are:

Icons:
- [ ] 1 'fish' 
- [ ] 1 'powerup'
- [ ] 5 'enemies' 

Soundtracks:
- [ ] 1 'Grommel' (not clear when this is triggered)
- [ ] 1 'Schurk' (not clear when this is triggered) 
- [ ] 1 'Main' which then needs to be reversed, sped up and slowed down

**Comment by clausmullie** [comment]
In terms of hard coding:

- [ ]  fish/sketch.js preloads the images with their unique name. I would propose naming 'enemy 1' and points this script to 'enemy 1' etc to make this easier to configure. Idem with for the soundtracks.

**Comment by clausmullie** [comment]
To make this project truly open and collaborative, we could also consider adding in (a link to) a newbie guide on how to compile into /docs/ so that it's easier to configure this game without breaking the project's current architecture.

**Comment by clausmullie** [comment]
In terms of documentation, we could include instructions to:

- [ ] Remove reference to fadrea
- [ ] Change title on the home page
- [ ] Change the 'info' blurb
- [ ] Explain how to get the highscores working

**Comment by clausmullie** [comment]
Another question - when is 'contact' between the fish and the enemy established? Is the contour of the enemy based on the 'shape' of the png image? or it is best to get a png image that matches the predefined 'shape' of the enemy?

**Comment by Jefwillems** [comment]
> Another question - when is 'contact' between the fish and the enemy established? Is the contour of the enemy based on the 'shape' of the png image? or it is best to get a png image that matches the predefined 'shape' of the enemy?

When you open the game you can type ```globalSettings.debug = true;``` in console and you will see the contours of enemies.

First of all, we'll need a new build system, as this one seems to be broken. I will start looking into using es6 modules with parcel-bundler this afternoon. expect an update ;-)

**Comment by Jefwillems** [comment]
I rewrote the app to use a more modern build system. It's now been merged into the master branch.

**Comment by clausmullie** [comment]
Awesome, thanks! I aim to dig deeper into this over the holidays.

**Comment by clausmullie** [comment]
closed :)
